# Generated by Django 4.1.6 on 2023-02-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_type',
            new_name='categoryType',
        ),
    ]
